### ISSUE TITLE
DefaultAnyExpTemplate - expands unwanted identifiers like true/false

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#363]
# Problem
we don't want certain identifiers like `true` to be picked up by 

```toml
RenderConfig.DefaultAnyExpTemplate = "{VarsPath}{AutoNameCopy()}"
```

because then `output_press = true;` gets expanded like below:

```
// Step 1: execute action `output_press = true;`
sm->vars.output_press = sm->vars.true;
```

# Workaround
For this particular case, we can use 1 and 0 instead of true and false.

# Better Fix
One idea is to allow simple expansions like 
```toml
Expansions = """
    true => true
    false => {AutoNameCopy()}
    """
```

To keep the implementation and usage simple, we won't allow expansions to refer to other expansions (or themselves).
