### ISSUE TITLE
feature - identifier expansion

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#367]
Could be used to help fix: https://github.com/StateSmith/StateSmith/issues/363

Idea:
```toml
IdentifierExpansions = """
    true => true
    false => {AutoNameCopy()}
    """
```
To keep the implementation and usage simple, we won't allow expansions to refer to other expansions (or themselves).
